routes/admin.php
<?php
/**
 * Created by PhpStorm.
 * User: Arthur
 * Date: 06/11/2018
 * Time: 13:22
 * Protect all with middleware pls don't forget
 */
Route::get('/','Admin\HomeController@getLogin')->name('admin.getLogin');
Route::post('/login','Admin\HomeController@adminLogin')->name('admin.Login');
Route::group(['middleware'=>'admin_auth'],function (){
    Route::get('/dashboard','Admin\HomeController@getDashboard')->name('admin.dashboard');
    Route::resources([
        'job-categories'=>'Admin\JobCategory',
        'item-categories'=>'Admin\Item\CategoryController',
        'item-sub-categories'=>'Admin\Item\SubCategoryController',
        'brands'=>'Admin\Brand\BrandController',
        'models'=>'Admin\Brand\ModelController',
        'item-sub-category-model'=>'Admin\Brand\ItemSubCategoryModelController',
    ]);

    Route::prefix('models')->group(function (){
        Route::get('categories/{id}','Admin\Brand\ModelController@getModelCategories');
    });
    //manage users
    Route::group(['prefix'=>'manage-users'],function (){
        Route::resources([
            'plans'=>'Admin\User\UserPlanController',
            'plan-features'=>'Admin\User\UserPlanFeatureController',
            'users'=>'Admin\UsersController',
        ]);
        //block users
        Route::put('block/{id}','Admin\UsersController@blockUser');
    });
    //settings
    Route::group(['prefix'=>'settings'],function (){
        Route::resources([
            'site'=>'Admin\Settings\SiteController',
        ]);
        Route::get('country/{id}','Admin\Settings\SiteController@getStates');
    });
    //manage companies
    Route::group(['prefix'=>'manage-companies'],function(){
        Route::get('verify','Admin\Company\ManageCompanyController@index')->name('manage.companies.verify');
        Route::post('verify','Admin\Company\ManageCompanyController@verify');
    });
    Route::get('/id',function (){
        dd(str_replace('-','',\Illuminate\Support\Str::uuid()));
    });
    Route::resources([
        'features'=>'Admin\Item\FeaturesController',
        'item-features'=>'Admin\Item\ItemFeaturesController'
    ]);
    Route::group(['prefix'=>'products'],function (){
        Route::get('approve','Admin\Item\ProductController@approve')->name('admin.products.approve');
        Route::get('approve/{id}','Admin\Item\ProductController@approveSingle');
        Route::post('approve-bulk','Admin\Item\ProductController@approveBulk');
    });
    //blog posts
    Route::group(['prefix'=>'blog'],function (){
        Route::resources([
            'posts'=>'Admin\Blog\PostController'
        ]);
    });
    Route::group(['prefix'=>'reports'],function (){
        Route::get('/jobs','Admin\ReportController@index')->name('admin.reports.index');
        Route::post('/filter-jobs','Admin\ReportController@filterRecords');
    });

    Route::get('profile','Admin\Profile\ProfileController@index')->name('admin.profile.index');
    Route::post('profile','Admin\Profile\ProfileController@update');
});
Route::get('/check-email',function(){
    return view('emails.company-registered');
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

use GuzzleHttp\Client;

Route::get('/', 'Misc\RegisterController@home')->name('user.home');
//password resets
Route::get('/password/reset', 'Auth\ForgotPasswordController@showLinkRequestForm')->name('password.reset');
Route::post('/password/email', 'Auth\ForgotPasswordController@sendResetLinkEmail')->name('password.email');
Route::get('/password/reset/{token}', 'Auth\ResetPasswordController@showResetForm')->name('password.reset.token');
Route::post('/password/reset', 'Auth\ResetPasswordController@reset');
Route::post('/register','Misc\RegisterController@register');
Route::post('/login','Misc\RegisterController@login');
Route::get('/user/verify/{token}', 'Misc\RegisterController@verifyUser');
Route::post('/home-search','Search\SearchController@homeSearch');
Route::get('/search','Search\SearchController@getResults');
Route::post('/search','Search\SearchController@filterResults');
//social login
Route::get('/login/{social}','Misc\RegisterController@socialLogin');
Route::get('/login/{social}/callback','Misc\RegisterController@handleProviderCallback');
Route::group(['middleware'=>'custom_auth'],function (){
    Route::get('/logout','Misc\RegisterController@logout')->name('user.logout');
    Route::get('/dashboard', 'HomeController@index')->name('home');
    Route::get('/settings','HomeController@settings')->name('dashboard.settings');
    Route::get('/messages','HomeController@messages')->name('dashboard.messages');
    Route::get('/messages/add/{id}','Misc\ChatController@addChat');
    Route::get('/bookmarks','HomeController@bookmarks')->name('dashboard.bookmarks');
    //reviews
    Route::get('/reviews/{paginate?}','HomeController@reviews')->name('dashboard.reviews');
    Route::get('/reviews-employees/{work_id}','HomeController@loadEmployeeForReview');
    Route::post('/reviews','HomeController@saveReview');
    Route::put('/reviews/{id}','HomeController@updateReview');
    Route::get('/contracts','HomeController@contract')->name('dashboard.contracts');
    //accept / decline
    Route::get('/contracts/accept/{id}','Interview\InterviewController@acceptContract');
    Route::get('/contracts/decline/{id}','Interview\InterviewController@declineContract');
    //dashboard notes
    Route::post('add-user-note','HomeController@addNote');
    Route::put('edit-user-note/{id}','HomeController@updateNote');
    Route::delete('delete-user-note/{id}','HomeController@deleteNote');
    //end of notes
    Route::post('/profile','Profile\UpdateController@update')->name('profile.update');
    //jobs
    Route::group(['middleware'=>'subscription.protection'],function (){
        Route::get('/manage-jobs/{paginate?}','Job\MiscController@manageJobs')->name('manage_jobs.all');
        Route::get('/manage-candidates/{slug}','Job\MiscController@getJobCandidates')->name('jobs.manage_candidates');
        Route::resources([
            'jobs'=>'Job\ManageJobController',
        ]);
        Route::get('/manage-jobs/search/filter','Job\MiscController@search');
    });

    //end of jobs
    Route::get('/find-jobs/{paginate?}','Job\FindController@index')->name('find_jobs.all');
    Route::post('/find-jobs/filter','Job\FindController@filter');
    Route::get('/cv/download/{id}','Job\MiscController@downloadCv')->name('profile.cv.download');
    Route::post('/apply/job','Job\MiscController@applyJob');
    Route::resources([
        'skills'=>'Profile\SkillController',
        'project'=>'Task\ManageTaskController',
        'subscriptions'=>'Subscription\SubscriptionController',
        'reviewjob'=>'Review\ReviewJobController',
        'reviewcompany'=>'Review\ReviewCompany'
    ]);
    Route::get('/jobs/bookmark/{id}','Job\ManageJobController@bookmarkWork');
    //add tags and requirements
    Route::post('add-work-tag','Job\MiscController@addTag');
    Route::delete('remove-work-tag/{id}','Job\MiscController@removeTag');
    Route::post('add-work-requirement','Job\MiscController@addRequirement');
    Route::delete('remove-work-requirement/{id}','Job\MiscController@removeRequirement');
//subscription checkout
    Route::group(['prefix'=>'subscriptions'],function (){
        Route::get('/checkout/{slug}/{type}','Subscription\SubscriptionController@checkout');
        Route::get('/checkout/order/{slug}/{type}','Subscription\SubscriptionController@processOrder');
        Route::get('/checkout/order/invoice/{slug}/{type}','Subscription\SubscriptionController@invoice')
            ->name('subscription.invoice');
        Route::post('/payments','Subscription\SubscriptionController@processPayment');
    });
    Route::get('/jobs/{slug}/apply','Job\MiscController@getApply')->name('jobs_apply.local');

    Route::get('/manage_task','Task\MiscController@managetask')->name('managetask');
    Route::get('/manage/{slug}/bidders','Task\MiscController@managebidders')->name('managebidders');
    Route::get('/active_bids','Task\MiscController@activebids')->name('activebids');
    Route::get('/project/{slug}/apply','Task\MiscController@project_apply')->name('project_apply');
    Route::post('/project/apply','Task\MiscController@apply')->name('apply_project');
    Route::post('/project/accept/application','Task\MiscController@accept_project')->name('accept_project');
    //endpoints
    Route::get('/endpoint/jobs','Misc\EndPointController@exposeJobs');
//user profile
    Route::get('/profile/{slug}','Profile\HomeController@index')->name('profile.user.in');
    //Route::get('/profile/remove-cv','Profile\HomeController@index')->name('profile.user.in');
    Route::get(str_slug('makeAllNotifications'),'Misc\ManageNotification@makeAllNotifications')->name('mark.all.notification');
    Route::get('/find-projects','Task\FindController@index')->name('find_projects.all');
    Route::get('/find-employees','Profile\FindEmployeeController@index')->name('find_employees.all');
    Route::post('/find-projects/filter','Task\FindController@filter');

    Route::get('/manage-candidates/{job_slug}/{applicant_slug}','Job\MiscController@showApplication')
        ->name('candidate.application.details');
    Route::get('/{job_slug}/{applicant_slug}/apply','Job\MiscController@acceptApply')
        ->name('candidate.application.details.apply');
    Route::get('/manage-candidates/{job_slug}/{applicant_slug}/interview','Interview\InterviewController@index')
        ->name('candidate.application.details.interview');
    Route::post('/manage-candidates/interview/save','Interview\InterviewController@store');
    Route::get('/interviews','Applicant\InterviewController@getInterviews')->name('applicants.interview');
    Route::get('/interviews/{id}','Interview\InterviewController@downloadAttachment');
    Route::get('/interviews/accept/{id}','Interview\InterviewController@acceptInterviewInvite');
    Route::get('/interviews/decline/{id}','Interview\InterviewController@declineInterviewInvitation');
    Route::get('/get-user-conversation/{id}','Misc\ChatController@getUserChatsById');
    Route::put('/mark-single-message-read/{id}','Misc\ChatController@markMessageAsRead');
    Route::post('/message-send','Misc\ChatController@send');
    Route::post('/message-add-chat','Misc\ChatController@createChat');
    Route::post('/interviews/send-contract','Interview\InterviewController@sendContract');
    Route::post('/interviews/postpone','Interview\InterviewController@postPoneInterview');
    //interview postpone
    Route::get('/interview-postpones','HomeController@postpone')
        ->name('employee.interview.postpone');
    Route::get('/interview-postpones/accept/{id}','Interview\InterviewController@acceptPostpone');
    Route::get('/interview-postpones/decline/{id}','Interview\InterviewController@declinePostpone');


//products ---->sell products
    Route::prefix('products')->group(function (){
        Route::resources([
            'sell'=>'Product\Sell\ProductController'
        ]);
        Route::get('my-posts/{paginate?}','Product\Sell\ProductController@myposts')->name('products.sell.my_posts');
        Route::prefix('end-point')->group(function (){
            Route::get('item-sub-categories/{id}','Product\Sell\ProductController@getItemSubCategories');
            Route::get('item-sub-categories-brands/{id}','Product\Sell\ProductController@getItemSubBrands');
            Route::get('brand-models/{id}','Product\Sell\ProductController@getBrandModels');
        });
        Route::get('buy','Product\Buy\ProductController@index')->name('products.buy.index');
        Route::get('buy/{slug}','Product\Buy\ProductController@productDetail')->name('product.buy.spec');
        Route::post('buy/filter','Product\Buy\ProductController@filterData');
        Route::post('buy/filter/map','Product\Buy\ProductController@getProductByLocation');
        Route::get('bookmark/{id}','Product\Buy\ProductController@bookmarkProduct');
        //all the following are methods used for updates
        Route::post('add-avatar','Product\Sell\ProductController@addAvatar');
        Route::delete('remove-avatar/{id}','Product\Sell\ProductController@removeAvatar');
        Route::post('add-contact','Product\Sell\ProductController@addContact');
        Route::delete('remove-contact/{id}','Product\Sell\ProductController@removeContact');
    });
//deal with bookmarks
    Route::get('/job/remove-bookmark/{id}','Job\ManageJobController@removeBookmark');

    //deal with all notifications
    Route::group(['prefix'=>'notifications'],function (){
        Route::get('mark/{id}','NotificationController@markSingle');
    });
    Route::get('check-ip',function (\Illuminate\Http\Request $request){
        dd($request->getClientIp());
    });

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Plan extends Model
{
    public function setNameAttribute($value){
        $this->attributes['name'] = title_case($value);
    }
    public function getMonthlyAmountAttribute($value){
        return number_format($value,2);
    }
    public function getYearlyAmountAttribute($value){
        return number_format($value,2);
    }
    public function features(){
        return $this->hasMany(PlanFeature::class,'plan_id');
    }
    public function subscriptions(){
        return $this->hasMany(Subscription::class);
    }

}

app/Models/Subscription.php
<?php

namespace App\Models;

use App\User;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use SanderVanHooft\Invoicable\IsInvoicable\IsInvoicableTrait;

class Subscription extends Model
{
    use IsInvoicableTrait;
    protected $fillable = ['user_id','trial_ends_at','end_at','user_id','plan_id','plan_type'];
    protected $hidden = ['id','created_at','updated_at'];
    public function getExpiredAttribute(){
        $now = Carbon::now();
        if(Carbon::parse($this->end_at)->gt($now)){
            return false;
        }
        return true;
    }
    protected $appends = ['expired'];
    public function user(){
        return $this->belongsTo(User::class);
    }
    public function plan(){
        return $this->belongsTo(Plan::class,'plan_id');
    }
}

resources/views/dashboard/subscriptions/checkout.blade.php
@extends('layouts.dashboard')

@section('content')
    <div class="dashboard-content-container" data-simplebar>
        <div class="dashboard-content-inner" >

            <!-- Dashboard Headline -->
            <div class="dashboard-headline">
                <h3>Subscriptions</h3>

                <!-- Breadcrumbs -->
                <nav id="breadcrumbs" class="dark">
                    <ul>
                        <li><a href="#">Dashboard</a></li>
                        <li>Pricing Plans</li>
                    </ul>
                </nav>
            </div>

            <!-- Row -->
            <checkout-component operators="{{$operators}}" settings="{{$settings}}" plan="{{$plan}}" type="{{$type}}"></checkout-component>
            <!-- Row / End -->

            <!-- Footer -->
            <div class="dashboard-footer-spacer"></div>
        @include('partials.auth.footer')
        <!-- Footer / End -->

        </div>
    </div>
@endsection
@section('dialogs')
    <div id="small-dialog-1" class="zoom-anim-dialog mfp-hide dialog-with-tabs">

        <!--Tabs -->
        <div class="sign-in-form">

            <ul class="popup-tabs-nav">
            </ul>

            <div class="popup-tabs-container">

                <!-- Tab -->
                <div class="popup-tab-content" id="tab1">

                    <!-- Welcome Text -->
                    <div class="welcome-text">
                        <h3>Change Review</h3>
                        <span>Rate <a href="#">Herman Ewout</a> for the project <a href="#">WordPress Theme Installation</a> </span>
                    </div>

                    <!-- Form -->
                    <form method="post" id="change-review-form">

                        <div class="feedback-yes-no">
                            <strong>Was this delivered on budget?</strong>
                            <div class="radio">
                                <input id="radio-rating-1" name="radio" type="radio" checked>
                                <label for="radio-rating-1"><span class="radio-label"></span> Yes</label>
                            </div>

                            <div class="radio">
                                <input id="radio-rating-2" name="radio" type="radio">
                                <label for="radio-rating-2"><span class="radio-label"></span> No</label>
                            </div>
                        </div>

                        <div class="feedback-yes-no">
                            <strong>Was this delivered on time?</strong>
                            <div class="radio">
                                <input id="radio-rating-3" name="radio2" type="radio" checked>
                                <label for="radio-rating-3"><span class="radio-label"></span> Yes</label>
                            </div>

                            <div class="radio">
                                <input id="radio-rating-4" name="radio2" type="radio">
                                <label for="radio-rating-4"><span class="radio-label"></span> No</label>
                            </div>
                        </div>

                        <div class="feedback-yes-no">
                            <strong>Your Rating</strong>
                            <div class="leave-rating">
                                <input type="radio" name="rating" id="rating-1" value="1" checked/>
                                <label for="rating-1" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-2" value="2"/>
                                <label for="rating-2" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-3" value="3"/>
                                <label for="rating-3" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-4" value="4"/>
                                <label for="rating-4" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-5" value="5"/>
                                <label for="rating-5" class="icon-material-outline-star"></label>
                            </div><div class="clearfix"></div>
                        </div>

                        <textarea class="with-border" placeholder="Comment" name="message" id="message" cols="7" required>Excellent programmer - helped me fixing small issue.</textarea>

                    </form>

                    <!-- Button -->
                    <button class="button full-width button-sliding-icon ripple-effect" type="submit" form="change-review-form">Save Changes <i class="icon-material-outline-arrow-right-alt"></i></button>

                </div>

            </div>
        </div>
    </div>
    <!-- Edit Review Popup / End -->


    <!-- Leave a Review for Freelancer Popup
    ================================================== -->
    <div id="small-dialog-2" class="zoom-anim-dialog mfp-hide dialog-with-tabs">

        <!--Tabs -->
        <div class="sign-in-form">

            <ul class="popup-tabs-nav">
            </ul>

            <div class="popup-tabs-container">

                <!-- Tab -->
                <div class="popup-tab-content" id="tab2">

                    <!-- Welcome Text -->
                    <div class="welcome-text">
                        <h3>Leave a Review</h3>
                        <span>Rate <a href="#">Peter Valentín</a> for the project <a href="#">Simple Chrome Extension</a> </span>
                    </div>

                    <!-- Form -->
                    <form method="post" id="leave-review-form">

                        <div class="feedback-yes-no">
                            <strong>Was this delivered on budget?</strong>
                            <div class="radio">
                                <input id="radio-1" name="radio" type="radio" required>
                                <label for="radio-1"><span class="radio-label"></span> Yes</label>
                            </div>

                            <div class="radio">
                                <input id="radio-2" name="radio" type="radio" required>
                                <label for="radio-2"><span class="radio-label"></span> No</label>
                            </div>
                        </div>

                        <div class="feedback-yes-no">
                            <strong>Was this delivered on time?</strong>
                            <div class="radio">
                                <input id="radio-3" name="radio2" type="radio" required>
                                <label for="radio-3"><span class="radio-label"></span> Yes</label>
                            </div>

                            <div class="radio">
                                <input id="radio-4" name="radio2" type="radio" required>
                                <label for="radio-4"><span class="radio-label"></span> No</label>
                            </div>
                        </div>

                        <div class="feedback-yes-no">
                            <strong>Your Rating</strong>
                            <div class="leave-rating">
                                <input type="radio" name="rating" id="rating-radio-1" value="1" required>
                                <label for="rating-radio-1" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-radio-2" value="2" required>
                                <label for="rating-radio-2" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-radio-3" value="3" required>
                                <label for="rating-radio-3" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-radio-4" value="4" required>
                                <label for="rating-radio-4" class="icon-material-outline-star"></label>
                                <input type="radio" name="rating" id="rating-radio-5" value="5" required>
                                <label for="rating-radio-5" class="icon-material-outline-star"></label>
                            </div><div class="clearfix"></div>
                        </div>

                        <textarea class="with-border" placeholder="Comment" name="message2" id="message2" cols="7" required></textarea>

                    </form>

                    <!-- Button -->
                    <button class="button full-width button-sliding-icon ripple-effect" type="submit" form="leave-review-form">Leave a Review <i class="icon-material-outline-arrow-right-alt"></i></button>

                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/dashboard/subscriptions/invoice.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>Hireo Invoice</title>
    <link rel="stylesheet" href="{{asset('css/invoice.css')}}">
    <style>
        #logo img{
            max-height: unset;
        }
    </style>
</head>

<body>

<!-- Print Button -->
<div class="print-button-container">
    <a href="javascript:window.print()" class="print-button">Print this invoice</a>
</div>

<!-- Invoice -->
<div id="invoice">

    <!-- Header -->
    <div class="row">
        <div class="col-xl-6">
            <div id="logo"><img style="height: 65px !important;" src="https://drive.google.com/uc?export=view&id=1mjqQpSTNffw5_VLtY49929zzaXTQfseC" alt=""></div>
        </div>

        <div class="col-xl-6">

            <p id="details">
                <strong>Order:</strong> {{$invoice->reference}} <br>
                <strong>Issued:</strong> {{\Carbon\Carbon::parse($invoice->created_at)->toFormattedDateString()}}
            </p>
        </div>
    </div>


    <!-- Client & Supplier -->
    <div class="row">
        <div class="col-xl-12">
            <h2>Invoice</h2>
        </div>

        <div class="col-xl-6">
            <strong class="margin-bottom-5">Supplier</strong>
            <p>
                Careersearch Ltd. <br>
                P.O. Box 23 <br>
                +233243742088 <br>
                Kumasi, Ashanti Region, Ghana <br>
            </p>
        </div>

        <div class="col-xl-6">
            <strong class="margin-bottom-5">Customer</strong>
            <p>
                {{$user->name}} <br>
                {{$user->profile->mobile}} <br>
                {{$user->email}} <br>
                {{$user->profile->location}}
            </p>
        </div>
    </div>


    <!-- Invoice -->
    <div class="row">
        <div class="col-xl-12">
            <table class="margin-top-20">
                <tr>
                    <th>Description</th>
                    <th>Price</th>
                    <th>Charges</th>
                    <th>Total</th>
                </tr>

                <tr>
                    <td>{{$plan->name}}</td>
                    @if(strtolower($subscription->plan_type) == 'month')
                        <td>GHS {{number_format($plan->monthly_amount,2)}}</td>
                        <td>GHS {{number_format(((float)$invoice->total - (float)$plan->monthly_amount),2)}}</td>
                        @else
                        <td>GHS {{number_format($plan->yearly_amount,2)}}</td>
                        <td>GHS {{number_format(((float)$invoice->total - (float)$plan->yearly_amount),2)}}</td>
                    @endif
                    <td>GHS {{number_format($invoice->total,2)}}</td>
                </tr>
            </table>
        </div>

        <div class="col-xl-4 col-xl-offset-8">
            <table id="totals">
                <tr>
                    <th>Total Payment</th>
                    <th><span>GHS {{number_format($invoice->total,2)}}</span></th>
                </tr>
            </table>
        </div>
    </div>


    <!-- Footer -->
    <div class="row">
        <div class="col-xl-12">
            <ul id="footer">
                <li><span>www.careersearch.com</span></li>
                <li>careersearch@tecunitgh.com</li>
                <li>(233) 24-374-2088</li>
            </ul>
        </div>
    </div>

</div>


</body>
</html>